export const HOME_MAIN_BASIC_INFO_AVATAR_SIZE = 60;
export const HOME_MAIN_DEFAULT_INFO_ACTION_BUTTON_SIZE = 50;
export const HOME_MAIN_DEFAULT_INFO_STREAK_ICON_SIZE = 16;
export const HOME_MAIN_DEFAULT_INFO_ACTION_ICON_SIZE = 25;